#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  8 11:40:22 2021

@author: pwhyx
"""
def function2():
    print('This text represent the content of function 2')  
    a = 5
    b = 7
    c = 9
    sum = a+b+c
    print('a =',a,'b =',b,'c =',c,'sum =',sum)
